import { buildLevel } from './generate'
import type { LevelDef } from './types'

export const LEVELS: LevelDef[] = [
  buildLevel({
    seed: 1101,
    theme: 'forest',
    id: 'floresta',
    name: 'Bosque Rosa',
    blurb: 'Três subidas curtas. Troca de lado e volta ao chão.',
    time: 240,
    zigzags: 3,
    climb: 2,
    cols: 132,
  }),
  buildLevel({
    seed: 2202,
    theme: 'ice',
    id: 'gelo',
    name: 'Pico Gelado',
    blurb: 'Quatro zigue-zagues baixos. O gelo escorrega.',
    time: 250,
    zigzags: 4,
    climb: 2,
    cols: 148,
  }),
  buildLevel({
    seed: 3303,
    theme: 'water',
    id: 'agua',
    name: 'Baía Aurora',
    blurb: 'Vários cais baixos. Embaixo só água.',
    time: 260,
    zigzags: 3,
    climb: 2,
    cols: 140,
  }),
  buildLevel({
    seed: 4404,
    theme: 'city',
    id: 'cidade',
    name: 'Centro Neon',
    blurb: 'Terraços curtos no vai-e-volta, depois a rua.',
    time: 270,
    zigzags: 4,
    climb: 2,
    cols: 154,
  }),
  {
    id: 'random',
    name: 'Vão Novo',
    theme: 'forest',
    blurb: 'O jogo monta a fase na hora. Cada entrada é outra.',
    time: 260,
    map: buildLevel({
      seed: 1,
      theme: 'forest',
      id: 'random',
      name: 'Vão Novo',
      blurb: '',
      time: 260,
      zigzags: 3,
      climb: 2,
    }).map,
    procedural: true,
  },
]
